### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Mesrine67** [Mycroft-Studios/FiveM-Dui-Boilerplate#2]
![image](https://github.com/Mycroft-Studios/FiveM-Dui-Boilerplate/assets/89279156/db0abd02-97bc-4498-9394-8d1ba55f84a5)
I can't write with the keyboard, do you have any ideas?

**Comment by Mycroft-Studios** [comment]
because that is not possible currently. the video is showcasing a PR that adds the ability, but it was rejected due to security concerns
